version: '3.4'

services:
  thegentlemanlibrary.api:
    image: ${DOCKER_REGISTRY-}thegentlemanlibraryapi
    build:
      context: .
      dockerfile: TheGentlemanLibrary.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
